# Generated by Django 5.0 on 2023-12-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especializacao', models.CharField(choices=[('Aves', 'Aves'), ('Gato', 'Gato'), ('Cães', 'Cães'), ('Outro', 'Outro')], max_length=255)),
            ],
        ),
    ]
