# Generated by Django 5.0 on 2023-12-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
