# Generated by Django 5.0 on 2023-12-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Veterinario', '0002_veterinario_telefone'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('observacao', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinario.veterinario')),
            ],
        ),
    ]
